sudo: required
language: python
python:
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"
  - "nightly"
addons:
  apt:
    packages:
      - unzip
      # Java8 Required for Sonar and SQLCL
      - oracle-java8-installer
      - oracle-java8-set-default
  sonarcloud:
    organization: crafti5-github
    token:
      secure: ${SONAR_TOKEN}
    branches:
      - master
before_install:
  - pip install coveralls
install:
  - pip install unittest-xml-reporting coverage pyyaml black ruff pylint
script:
  - black --check --diff .
  - ruff check .
  - pylint **/*.py --exit-zero
  - cd tests
  - coverage run --branch --source=../ tests.py
  - coverage xml -i
  - cd ..
  - sonar-scanner
  - cd tests
  - coverage run --branch --source=../ tests.py
after_success:
    - coveralls